let testArray = [1,2,3,4,5,6,7,8,9]
for(let i = 0; i < testArray.length; i++){
    if(testArray[i] % 2 == 0){
        // console.log(testArray[i] + 3)
    }
    // console.log(testArray[i])
}

let testObjectArray = [
    {name:"Stan", age:30, occupation:"Carpenter"},
    {name:"Adam", age:17, occupation:"Food Manager"},
    {name:"Tami", age:52, occupation:"Life insurance"},
]
for(let i = 0; i < testObjectArray.length; i++){
    const obj = testObjectArray[i];
    console.log(`Name: ${obj.name}, Age: ${obj.age}, Occupation: ${obj.occupation}`)
}

console.log(testArray.sort((a,b) => b-a))
console.log(testObjectArray.sort((a,b) => a.age - b.age))














let data = [{"first_name":"Kaylil","last_name":"Kubik","Domains":"umn.edu","Slogan":"matrix synergistic schemas"},
{"first_name":"Miof mela","last_name":"Loynes","Domains":"nydailynews.com","Slogan":"visualize 24/7 niches"},
{"first_name":"Amii","last_name":"MacCarroll","Domains":"tinypic.com","Slogan":"scale world-class interfaces"},
{"first_name":"Bev","last_name":"Purton","Domains":"go.com","Slogan":"optimize virtual mindshare"},
{"first_name":"Sawyer","last_name":"Skullet","Domains":"whitehouse.gov","Slogan":"orchestrate viral systems"},
{"first_name":"Lew","last_name":"Linforth","Domains":"posterous.com","Slogan":"streamline killer content"},
{"first_name":"Aymer","last_name":"Kingscott","Domains":"cnbc.com","Slogan":"optimize sexy metrics"},
{"first_name":"Hobart","last_name":"Potzold","Domains":"slate.com","Slogan":"exploit customized eyeballs"},
{"first_name":"Loree","last_name":"Fayer","Domains":"ca.gov","Slogan":"recontextualize web-enabled networks"},
{"first_name":"Kiri","last_name":"Mercy","Domains":"jugem.jp","Slogan":"reinvent customized networks"},
{"first_name":"Elysha","last_name":"Fenelow","Domains":"nba.com","Slogan":"exploit holistic synergies"},
{"first_name":"Moses","last_name":"Cutting","Domains":"ed.gov","Slogan":"maximize dynamic portals"},
{"first_name":"Anya","last_name":"Pennini","Domains":"microsoft.com","Slogan":"evolve innovative schemas"},
{"first_name":"Trude","last_name":"Kasting","Domains":"people.com.cn","Slogan":"unleash B2C niches"},
{"first_name":"Charissa","last_name":"Kochlin","Domains":"gizmodo.com","Slogan":"redefine viral e-tailers"},
{"first_name":"Cornelle","last_name":"Bice","Domains":"wordpress.org","Slogan":"reinvent 24/7 solutions"},
{"first_name":"Brocky","last_name":"Couser","Domains":"smh.com.au","Slogan":"harness magnetic networks"},
{"first_name":"Avril","last_name":"Jacox","Domains":"purevolume.com","Slogan":"strategize robust communities"},
{"first_name":"Babette","last_name":"Ritchley","Domains":"admin.ch","Slogan":"reinvent end-to-end content"},
{"first_name":"Georgia","last_name":"Depka","Domains":"google.com.hk","Slogan":"reintermediate turn-key applications"},
{"first_name":"Kevan","last_name":"Harkins","Domains":"economist.com","Slogan":"engineer out-of-the-box relationships"},
{"first_name":"Renate","last_name":"Graeme","Domains":"china.com.cn","Slogan":"deploy mission-critical users"},
{"first_name":"Anne-corinne","last_name":"Crosher","Domains":"sina.com.cn","Slogan":"transition dot-com users"},
{"first_name":"Otes","last_name":"Pullan","Domains":"php.net","Slogan":"integrate innovative relationships"},
{"first_name":"Mildrid","last_name":"Searl","Domains":"arstechnica.com","Slogan":"utilize web-enabled eyeballs"},
{"first_name":"Frans","last_name":"Cullotey","Domains":"spotify.com","Slogan":"architect open-source web-readiness"},
{"first_name":"Sabrina","last_name":"Treadway","Domains":"archive.org","Slogan":"aggregate frictionless schemas"},
{"first_name":"Dmitri","last_name":"Samme","Domains":"github.com","Slogan":"innovate seamless ROI"},
{"first_name":"Bert","last_name":"Palfreman","Domains":"va.gov","Slogan":"optimize scalable interfaces"},
{"first_name":"Lammond","last_name":"Penni","Domains":"qq.com","Slogan":"empower interactive mindshare"},
{"first_name":"Jacqueline","last_name":"Askam","Domains":"abc.net.au","Slogan":"reintermediate compelling initiatives"},
{"first_name":"Lexi","last_name":"Gumme","Domains":"prnewswire.com","Slogan":"e-enable cross-media interfaces"},
{"first_name":"Corrina","last_name":"Keppel","Domains":"unc.edu","Slogan":"enhance 24/7 markets"},
{"first_name":"Nikos","last_name":"Giacubo","Domains":"google.ru","Slogan":"engineer dynamic vortals"},
{"first_name":"Hendrika","last_name":"Lightbody","Domains":"com.com","Slogan":"brand wireless eyeballs"},
{"first_name":"Craig","last_name":"Dorgan","Domains":"paginegialle.it","Slogan":"brand viral solutions"},
{"first_name":"Rania","last_name":"Caush","Domains":"behance.net","Slogan":"synthesize cutting-edge technologies"},
{"first_name":"Emmalynn","last_name":"Camosso","Domains":"mysql.com","Slogan":"syndicate extensible deliverables"},
{"first_name":"Binny","last_name":"Fitchew","Domains":"ihg.com","Slogan":"benchmark impactful convergence"},
{"first_name":"Allina","last_name":"Binton","Domains":"smugmug.com","Slogan":"visualize vertical infrastructures"},
{"first_name":"Torre","last_name":"Bigham","Domains":"addthis.com","Slogan":"exploit world-class e-markets"},
{"first_name":"Gertrudis","last_name":"Scandrite","Domains":"bloglines.com","Slogan":"grow robust synergies"},
{"first_name":"Tammara","last_name":"Rubie","Domains":"shareasale.com","Slogan":"synergize seamless functionalities"},
{"first_name":"Tandie","last_name":"Fennell","Domains":"lulu.com","Slogan":"innovate robust interfaces"},
{"first_name":"Puff","last_name":"Holburn","Domains":"oaic.gov.au","Slogan":"cultivate front-end metrics"},
{"first_name":"Lorelei","last_name":"Szymonwicz","Domains":"hp.com","Slogan":"brand bleeding-edge partnerships"},
{"first_name":"Viole","last_name":"Sleet","Domains":"github.io","Slogan":"transition one-to-one vortals"},
{"first_name":"Arielle","last_name":"Jutson","Domains":"businessinsider.com","Slogan":"revolutionize granular users"},
{"first_name":"Katrina","last_name":"Dominik","Domains":"hibu.com","Slogan":"unleash sticky relationships"},
{"first_name":"Esteban","last_name":"Appleyard","Domains":"deliciousdays.com","Slogan":"leverage granular web services"},
{"first_name":"Ruthy","last_name":"MacLardie","Domains":"canalblog.com","Slogan":"innovate mission-critical architectures"},
{"first_name":"Hillary","last_name":"Feige","Domains":"plala.or.jp","Slogan":"deploy clicks-and-mortar web services"},
{"first_name":"Darcie","last_name":"Josland","Domains":"sphinn.com","Slogan":"streamline dot-com web services"},
{"first_name":"Torie","last_name":"Baly","Domains":"wordpress.com","Slogan":"syndicate transparent solutions"},
{"first_name":"Ellsworth","last_name":"Rowlings","Domains":"chicagotribune.com","Slogan":"unleash cutting-edge convergence"},
{"first_name":"Kerk","last_name":"Dries","Domains":"sogou.com","Slogan":"disintermediate seamless systems"},
{"first_name":"Joy","last_name":"Keech","Domains":"sogou.com","Slogan":"exploit efficient portals"},
{"first_name":"Camella","last_name":"Littler","Domains":"de.vu","Slogan":"enhance virtual ROI"},
{"first_name":"Coriss","last_name":"Falvey","Domains":"hibu.com","Slogan":"enhance integrated mindshare"},
{"first_name":"Melania","last_name":"Woodward","Domains":"pen.io","Slogan":"scale scalable users"},
{"first_name":"Leola","last_name":"Gelland","Domains":"google.ru","Slogan":"revolutionize real-time portals"},
{"first_name":"Tabb","last_name":"De Antoni","Domains":"ca.gov","Slogan":"generate web-enabled partnerships"},
{"first_name":"Ophelia","last_name":"Coronas","Domains":"addthis.com","Slogan":"generate viral vortals"},
{"first_name":"Karalynn","last_name":"Dybell","Domains":"rambler.ru","Slogan":"mesh open-source architectures"},
{"first_name":"Odie","last_name":"Lorenzo","Domains":"cbc.ca","Slogan":"utilize killer portals"},
{"first_name":"Bear","last_name":"Killingbeck","Domains":"bandcamp.com","Slogan":"transform dot-com models"},
{"first_name":"Ervin","last_name":"Shropsheir","Domains":"webnode.com","Slogan":"innovate collaborative action-items"},
{"first_name":"Gabey","last_name":"Capini","Domains":"alexa.com","Slogan":"grow enterprise web services"},
{"first_name":"Caddric","last_name":"Keyzor","Domains":"thetimes.co.uk","Slogan":"optimize real-time paradigms"},
{"first_name":"Saunder","last_name":"Charlwood","Domains":"spiegel.de","Slogan":"maximize magnetic communities"},
{"first_name":"Roshelle","last_name":"Minchinton","Domains":"indiatimes.com","Slogan":"transition distributed initiatives"},
{"first_name":"Olag","last_name":"Sabathe","Domains":"nbcnews.com","Slogan":"reinvent distributed functionalities"},
{"first_name":"Annelise","last_name":"Forgan","Domains":"networksolutions.com","Slogan":"disintermediate plug-and-play bandwidth"},
{"first_name":"Deeann","last_name":"Togher","Domains":"timesonline.co.uk","Slogan":"innovate frictionless e-commerce"},
{"first_name":"Jae","last_name":"Highton","Domains":"ebay.com","Slogan":"cultivate out-of-the-box deliverables"},
{"first_name":"Tansy","last_name":"Beddow","Domains":"livejournal.com","Slogan":"whiteboard robust partnerships"},
{"first_name":"Kelbee","last_name":"Marzello","Domains":"newsvine.com","Slogan":"transform back-end supply-chains"},
{"first_name":"Harmonia","last_name":"Shilstone","Domains":"theglobeandmail.com","Slogan":"exploit viral convergence"},
{"first_name":"Thedrick","last_name":"Troake","Domains":"cbc.ca","Slogan":"leverage integrated portals"},
{"first_name":"Gorden","last_name":"Morrid","Domains":"networkadvertising.org","Slogan":"extend e-business e-commerce"},
{"first_name":"Janna","last_name":"Prandy","Domains":"rakuten.co.jp","Slogan":"synthesize sticky portals"},
{"first_name":"Jarrid","last_name":"Frigot","Domains":"google.co.jp","Slogan":"streamline out-of-the-box deliverables"},
{"first_name":"Felicdad","last_name":"Bowyer","Domains":"example.com","Slogan":"leverage mission-critical web-readiness"},
{"first_name":"Deanna","last_name":"Hoodspeth","Domains":"weibo.com","Slogan":"transform seamless functionalities"},
{"first_name":"Alvie","last_name":"Kernar","Domains":"cdbaby.com","Slogan":"harness sticky e-tailers"},
{"first_name":"Billi","last_name":"Meharg","Domains":"boston.com","Slogan":"revolutionize cutting-edge functionalities"},
{"first_name":"Edie","last_name":"Szymon","Domains":"umich.edu","Slogan":"productize efficient applications"},
{"first_name":"Tore","last_name":"Tubble","Domains":"phoca.cz","Slogan":"reinvent dot-com models"},
{"first_name":"Dina","last_name":"Gilffillan","Domains":"instagram.com","Slogan":"cultivate sexy solutions"},
{"first_name":"Aluin","last_name":"Tweed","Domains":"time.com","Slogan":"repurpose B2B solutions"},
{"first_name":"Wesley","last_name":"Petriello","Domains":"flavors.me","Slogan":"redefine 24/7 paradigms"},
{"first_name":"Janeva","last_name":"Asser","Domains":"irs.gov","Slogan":"incubate dot-com networks"},
{"first_name":"Sheelagh","last_name":"Morrieson","Domains":"nbcnews.com","Slogan":"drive rich e-services"},
{"first_name":"Nonna","last_name":"Pessler","Domains":"chicagotribune.com","Slogan":"implement user-centric experiences"},
{"first_name":"Conney","last_name":"Ovitts","Domains":"comcast.net","Slogan":"incentivize viral e-commerce"},
{"first_name":"Amery","last_name":"Rosewarne","Domains":"indiatimes.com","Slogan":"generate integrated content"},
{"first_name":"Tremain","last_name":"Girardez","Domains":"ebay.com","Slogan":"morph robust vortals"},
{"first_name":"Noelani","last_name":"Heinish","Domains":"eventbrite.com","Slogan":"engage dynamic portals"},
{"first_name":"Humbert","last_name":"Simmgen","Domains":"fema.gov","Slogan":"evolve sticky models"},
{"first_name":"Rebeka","last_name":"Pllu","Domains":"theglobeandmail.com","Slogan":"orchestrate leading-edge schemas"},
{"first_name":"Burg","last_name":"Rexworthy","Domains":"blinklist.com","Slogan":"redefine clicks-and-mortar niches"},
{"first_name":"Ricardo","last_name":"McFadden","Domains":"cnet.com","Slogan":"seize world-class partnerships"},
{"first_name":"Chrisy","last_name":"Bisiker","Domains":"theguardian.com","Slogan":"evolve proactive deliverables"},
{"first_name":"Nathanial","last_name":"Wolters","Domains":"arizona.edu","Slogan":"scale 24/7 markets"},
{"first_name":"Moises","last_name":"Bullene","Domains":"163.com","Slogan":"morph robust communities"},
{"first_name":"Henriette","last_name":"Goom","Domains":"bandcamp.com","Slogan":"exploit compelling communities"},
{"first_name":"Land","last_name":"Butterick","Domains":"ocn.ne.jp","Slogan":"enhance intuitive eyeballs"},
{"first_name":"Fae","last_name":"Ellicott","Domains":"wired.com","Slogan":"monetize real-time web-readiness"},
{"first_name":"Taite","last_name":"Byart","Domains":"jiathis.com","Slogan":"redefine proactive partnerships"},
{"first_name":"Thane","last_name":"Sedgwick","Domains":"oakley.com","Slogan":"deploy bricks-and-clicks e-services"},
{"first_name":"Joyce","last_name":"Stokoe","Domains":"hostgator.com","Slogan":"reintermediate user-centric infrastructures"},
{"first_name":"Idalia","last_name":"Coal","Domains":"yellowbook.com","Slogan":"innovate distributed synergies"},
{"first_name":"Riane","last_name":"Flag","Domains":"washingtonpost.com","Slogan":"disintermediate user-centric supply-chains"},
{"first_name":"Mellisent","last_name":"Loades","Domains":"yellowpages.com","Slogan":"synthesize killer web-readiness"},
{"first_name":"Elana","last_name":"Fowley","Domains":"naver.com","Slogan":"innovate cutting-edge paradigms"},
{"first_name":"Baron","last_name":"Hemshall","Domains":"umn.edu","Slogan":"exploit vertical networks"},
{"first_name":"Sigvard","last_name":"Betterton","Domains":"addtoany.com","Slogan":"transition open-source bandwidth"},
{"first_name":"Katusha","last_name":"Van der Baaren","Domains":"dropbox.com","Slogan":"orchestrate out-of-the-box initiatives"},
{"first_name":"Mariska","last_name":"Scholler","Domains":"dropbox.com","Slogan":"streamline sticky applications"},
{"first_name":"Fabien","last_name":"Lyddiard","Domains":"bandcamp.com","Slogan":"optimize killer paradigms"},
{"first_name":"Carly","last_name":"Kopecka","Domains":"reverbnation.com","Slogan":"monetize world-class eyeballs"},
{"first_name":"Lauritz","last_name":"Cammocke","Domains":"tripadvisor.com","Slogan":"utilize B2B channels"},
{"first_name":"Ara","last_name":"Poynser","Domains":"arstechnica.com","Slogan":"expedite scalable infrastructures"},
{"first_name":"Ingrid","last_name":"Selvey","Domains":"who.int","Slogan":"reinvent dynamic content"},
{"first_name":"Itch","last_name":"Blaskett","Domains":"wunderground.com","Slogan":"incubate one-to-one supply-chains"},
{"first_name":"Gavin","last_name":"Read","Domains":"java.com","Slogan":"implement e-business networks"},
{"first_name":"Templeton","last_name":"McCurtain","Domains":"unc.edu","Slogan":"orchestrate sexy eyeballs"},
{"first_name":"Tadd","last_name":"Karolczyk","Domains":"etsy.com","Slogan":"syndicate front-end synergies"},
{"first_name":"Rustin","last_name":"Furtado","Domains":"squarespace.com","Slogan":"whiteboard 24/7 ROI"},
{"first_name":"Howey","last_name":"Smeaton","Domains":"jugem.jp","Slogan":"incentivize next-generation channels"},
{"first_name":"Bard","last_name":"Anfusso","Domains":"wikia.com","Slogan":"brand enterprise markets"},
{"first_name":"Siusan","last_name":"Stone","Domains":"berkeley.edu","Slogan":"aggregate strategic eyeballs"},
{"first_name":"Sloan","last_name":"Tack","Domains":"abc.net.au","Slogan":"incubate e-business vortals"},
{"first_name":"Jaquenetta","last_name":"Patry","Domains":"fotki.com","Slogan":"incubate global ROI"},
{"first_name":"Datha","last_name":"De Gowe","Domains":"imgur.com","Slogan":"redefine seamless web services"},
{"first_name":"Anthony","last_name":"Chetwynd","Domains":"ameblo.jp","Slogan":"harness synergistic deliverables"},
{"first_name":"Cal","last_name":"O'Corrane","Domains":"ycombinator.com","Slogan":"enhance scalable interfaces"},
{"first_name":"Arvie","last_name":"Mowne","Domains":"surveymonkey.com","Slogan":"scale compelling vortals"},
{"first_name":"Eolanda","last_name":"Scohier","Domains":"wikipedia.org","Slogan":"integrate 24/365 ROI"},
{"first_name":"Gabbi","last_name":"Feehan","Domains":"drupal.org","Slogan":"morph dot-com initiatives"},
{"first_name":"Tadd","last_name":"Echlin","Domains":"telegraph.co.uk","Slogan":"matrix collaborative experiences"},
{"first_name":"Darnell","last_name":"Steart","Domains":"google.pl","Slogan":"embrace front-end initiatives"},
{"first_name":"Jasmine","last_name":"Shawley","Domains":"nymag.com","Slogan":"engage bleeding-edge action-items"},
{"first_name":"Hedda","last_name":"Pudsey","Domains":"shinystat.com","Slogan":"utilize frictionless infrastructures"},
{"first_name":"Harbert","last_name":"Mucklestone","Domains":"cocolog-nifty.com","Slogan":"syndicate proactive platforms"},
{"first_name":"Sanson","last_name":"Glenton","Domains":"xrea.com","Slogan":"redefine one-to-one experiences"},
{"first_name":"Astra","last_name":"Negro","Domains":"state.tx.us","Slogan":"redefine magnetic deliverables"},
{"first_name":"Dionysus","last_name":"Birchall","Domains":"goo.gl","Slogan":"synthesize customized vortals"},
{"first_name":"Stoddard","last_name":"Dobbison","Domains":"linkedin.com","Slogan":"transition frictionless paradigms"},
{"first_name":"Sanders","last_name":"Wanstall","Domains":"gravatar.com","Slogan":"reinvent innovative synergies"},
{"first_name":"Essy","last_name":"Grimsditch","Domains":"issuu.com","Slogan":"engineer efficient technologies"},
{"first_name":"Erich","last_name":"Daubney","Domains":"jugem.jp","Slogan":"streamline impactful infrastructures"},
{"first_name":"Gaby","last_name":"Byart","Domains":"nba.com","Slogan":"reintermediate 24/7 mindshare"},
{"first_name":"Antonietta","last_name":"McQueen","Domains":"slashdot.org","Slogan":"orchestrate intuitive schemas"},
{"first_name":"Hedda","last_name":"Henkens","Domains":"arizona.edu","Slogan":"disintermediate transparent ROI"},
{"first_name":"Arty","last_name":"Levens","Domains":"meetup.com","Slogan":"strategize transparent infrastructures"},
{"first_name":"Farlee","last_name":"Ashbridge","Domains":"abc.net.au","Slogan":"strategize revolutionary e-business"},
{"first_name":"Fidelio","last_name":"Raimbauld","Domains":"china.com.cn","Slogan":"optimize dynamic users"},
{"first_name":"Claudell","last_name":"Balch","Domains":"about.com","Slogan":"drive open-source convergence"},
{"first_name":"Emmeline","last_name":"Beauchop","Domains":"loc.gov","Slogan":"incentivize intuitive e-business"},
{"first_name":"Harald","last_name":"Ensten","Domains":"whitehouse.gov","Slogan":"cultivate innovative methodologies"},
{"first_name":"Beniamino","last_name":"Binge","Domains":"reddit.com","Slogan":"enable holistic bandwidth"},
{"first_name":"Tedda","last_name":"Morecomb","Domains":"icq.com","Slogan":"e-enable global infrastructures"},
{"first_name":"Kerwin","last_name":"Hartrick","Domains":"salon.com","Slogan":"generate e-business portals"},
{"first_name":"Mabel","last_name":"Dallan","Domains":"bravesites.com","Slogan":"architect magnetic content"},
{"first_name":"Kitti","last_name":"Shellum","Domains":"altervista.org","Slogan":"integrate scalable initiatives"},
{"first_name":"Gav","last_name":"Sealeaf","Domains":"uol.com.br","Slogan":"engineer out-of-the-box markets"},
{"first_name":"Jeanette","last_name":"Lazer","Domains":"technorati.com","Slogan":"utilize strategic vortals"},
{"first_name":"Essa","last_name":"Godfree","Domains":"nytimes.com","Slogan":"deploy scalable relationships"},
{"first_name":"Riva","last_name":"Bolesma","Domains":"forbes.com","Slogan":"leverage vertical infrastructures"},
{"first_name":"Willy","last_name":"Giacopelo","Domains":"independent.co.uk","Slogan":"engage 24/365 markets"},
{"first_name":"Rickard","last_name":"Shillaker","Domains":"yellowbook.com","Slogan":"evolve enterprise solutions"},
{"first_name":"Jeno","last_name":"Hansill","Domains":"homestead.com","Slogan":"integrate bricks-and-clicks markets"},
{"first_name":"Conrade","last_name":"Gyenes","Domains":"amazon.co.jp","Slogan":"target scalable e-markets"},
{"first_name":"Hildy","last_name":"Ivanilov","Domains":"hubpages.com","Slogan":"maximize collaborative convergence"},
{"first_name":"Lindy","last_name":"Winson","Domains":"shutterfly.com","Slogan":"extend virtual methodologies"},
{"first_name":"Saidee","last_name":"Wolfarth","Domains":"tinypic.com","Slogan":"transform revolutionary synergies"},
{"first_name":"Filia","last_name":"Saben","Domains":"paypal.com","Slogan":"whiteboard turn-key initiatives"},
{"first_name":"Kimberlyn","last_name":"Ottiwill","Domains":"yolasite.com","Slogan":"evolve sticky applications"},
{"first_name":"Heidie","last_name":"Azemar","Domains":"cargocollective.com","Slogan":"optimize cross-platform channels"},
{"first_name":"Joline","last_name":"Hambrick","Domains":"cocolog-nifty.com","Slogan":"morph scalable portals"},
{"first_name":"Karilynn","last_name":"Perutto","Domains":"hugedomains.com","Slogan":"utilize integrated markets"},
{"first_name":"Teddi","last_name":"Roja","Domains":"kickstarter.com","Slogan":"engage extensible e-tailers"},
{"first_name":"Moll","last_name":"Hynard","Domains":"timesonline.co.uk","Slogan":"streamline intuitive systems"},
{"first_name":"Nial","last_name":"Minguet","Domains":"flickr.com","Slogan":"synergize bricks-and-clicks solutions"},
{"first_name":"Ollie","last_name":"Moen","Domains":"craigslist.org","Slogan":"unleash vertical initiatives"},
{"first_name":"Germain","last_name":"Scone","Domains":"mozilla.com","Slogan":"extend scalable e-markets"},
{"first_name":"Adriena","last_name":"Ree","Domains":"goo.ne.jp","Slogan":"reinvent 24/365 technologies"},
{"first_name":"Ikey","last_name":"Fillimore","Domains":"blinklist.com","Slogan":"reintermediate B2C deliverables"},
{"first_name":"Tracy","last_name":"Gronou","Domains":"geocities.com","Slogan":"repurpose leading-edge portals"},
{"first_name":"Dev","last_name":"Sallows","Domains":"amazon.co.jp","Slogan":"engineer e-business users"},
{"first_name":"Meier","last_name":"Gilgryst","Domains":"prweb.com","Slogan":"disintermediate strategic metrics"},
{"first_name":"Beverly","last_name":"Mc-Kerley","Domains":"webs.com","Slogan":"innovate vertical markets"},
{"first_name":"Rozele","last_name":"Milch","Domains":"desdev.cn","Slogan":"streamline holistic vortals"},
{"first_name":"Maximilian","last_name":"Connor","Domains":"behance.net","Slogan":"aggregate robust e-markets"},
{"first_name":"Addie","last_name":"Woolhouse","Domains":"timesonline.co.uk","Slogan":"scale wireless communities"},
{"first_name":"Sharlene","last_name":"Copelli","Domains":"t.co","Slogan":"facilitate interactive e-commerce"},
{"first_name":"Shay","last_name":"Mattheis","Domains":"sitemeter.com","Slogan":"whiteboard wireless web services"},
{"first_name":"Antoni","last_name":"Allitt","Domains":"skyrock.com","Slogan":"generate turn-key initiatives"},
{"first_name":"Peri","last_name":"Gergely","Domains":"economist.com","Slogan":"expedite turn-key methodologies"}]